version: '3.7'

services:
  db:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run dev
